apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: rabbitmq-cluster-operator-rabbitmq-system-edit
rules:
  - apiGroups:
      - rabbitmq.com
    resources:
      - rabbitmqclusters
      - rabbitmqclusters/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
